config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :categories, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
    resources :reviews, only: [ :new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
  resources :reviews, only: [ :destroy ]
  root "categories#index"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :recipe
  belongs_to :category

  validates :comment, length: { minimum: 6 }
  validates :recipe, uniqueness: { scope: :category }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :recipes, through: :bookmarks
  has_many :reviews, dependent: :destroy
  # has_one_attached :photo

  validates :name, uniqueness: true

  private

  # def default_category_image(category_name)
  #   # raise
  #   default_images = {
  #     "Desserts" => "desserts-placeholder.jpg",
  #     "Main Courses" => "main-course-placeholder.jpg",
  #     "Breakfast" => "breakfast-placeholder.jpg",
  #     "Drinks" => "drink-placeholder.jpg",
  #     "Quick-Fix" => "quick-fix-placeholder.jpg",
  #     "Appetizers" => "appetizers-placeholder",
  #     "Gluten-Free" => "gluten-free-placeholder.jpg",
  #     "Vegetarian" => "vegetarian-placeholder.jpg"
  #   }

  #   # Return the image or a default one if the category name is not found
  #   default_images[category_name] || "main-course-placeholder.jpg"
  # end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :bookmarks
  has_many :categories, through: :bookmarks

  validates :name, presence: true, uniqueness: true
  validates :rating, inclusion: { in: 0..10 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :category

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @category = Category.find(params[:category_id])
    @bookmark = Bookmark.new
  end

  def create
    @category = Category.find_by(id: params[:category_id])
    @bookmark = @category.bookmarks.new(bookmark_params)
    if @bookmark.save
      redirect_to category_path(@category), notice: "Bookmark successfully added"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    # raise
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to category_path, notice: "Bookmark successfully deleted"
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :recipe_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @bookmarks = @category.bookmarks.includes(:recipe)
    @reviews = @category.reviews
    @review = Review.new
  end

  def new
    @category = Category.new
    @default_image_urls = {
        "Desserts" => { name: "Desserts", url: "desserts-placeholder.jpg" },
        "Main Courses" => { name: "Main Courses", url: "main-course-placeholder.jpg" },
        "Breakfast" => { name: "Breakfast", url: "breakfast-placeholder.jpg" },
        "Drinks" => { name: "Drinks", url: "drinks-placeholder.jpg" },
        "Quick-Fix" => { name: "Quick-Fix", url: "quick-fix-placeholder.jpg" },
        "Appetizers" => { name: "Appetizers", url: "appetizers-placeholder.jpg" },
        "Gluten-Free" => { name: "Gluten-Free", url: "gluten-free-placeholder.jpg" },
        "Vegetarian" => { name: "Vegetarian", url: "vegetarian-placeholder.jpg" }
      }
  end

  def create
    @category = Category.new(category_params)

    if params[:category][:image].present?
      uploaded_image = Cloudinary::Uploader.upload(params[:category][:image])
      @category.image = uploaded_image["secure_url"]
    elsif params[:category][:default_image].present?
      @category.image = params[:category][:default_image]
    end

    if @category.save
      redirect_to category_path(@category), notice: "Category successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    raise
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path, status: :see_other
  end

  private

  def category_params
    params.require(:category).permit(:name, :image, :default_image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_category, only: [ :new, :create ]

  def new
    @review = @category.reviews.new
  end

  def create
    # raise
    @review = @category.reviews.new(review_params)
    if @review.save
      redirect_to category_path(@category), notice: "Review added successfully"
    else
      @bookmarks = @category.bookmarks.includes(:recipe) # Ensures bookmarks are available
      @reviews = @category.reviews
      render "categories/show", status: :unprocessable_entity
      # redirect_to category_path(@category), notice: "Review can't be blank"
    end
  end

  def destroy
    # raise
    @review = Review.find(params[:id])
    # logger.debug "Attempting to delete review with ID: #{@review.id}"
    # logger.debug "Review content: #{@review.content}"
    if @review.destroy
    # logger.debug "Review successfully deleted"
    redirect_to category_path, notice: "Review successfully deleted"
    else
    # logger.debug "Failed to delete review"
    redirect_to category_path(@category), alert: "Failed to delete review"
    end
  end

  private

  def set_category
    @category = Category.find(params[:category_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
# app/helpers/application_helper.rb or app/helpers/categories_helper.rb
module ApplicationHelper
  # Define a method to return default category images
  def default_category_image(category_name)
    # raise
    default_images = {
      "Desserts" => "desserts-placeholder.jpg",
      "Main Courses" => "main-course-placeholder.jpg",
      "Breakfast" => "breakfast-placeholder.jpg",
      "Drinks" => "drinks-placeholder.jpg",
      "Quick-Fix" => "quick-fix-placeholder.jpg",
      "Appetizers" => "appetizers-placeholder.jpg",
      "Gluten-Free" => "gluten-free-placeholder.jpg",
      "Vegetarian" => "vegetarian-placeholder.jpg"
    }

    # Return the image or a default one if the category name is not found
    default_images[category_name] || "main-course-placeholder.jpg"
  end

  # def default_image_urls
  #   {
  #     "Desserts" => { name: "Desserts", url: "desserts-placeholder.jpg" },
  #     "Main Courses" => { name: "Main Courses", url: "main-course-placeholder.jpg" },
  #     "Breakfast" => { name: "Breakfast", url: "breakfast-placeholder.jpg" },
  #     "Drinks" => { name: "Drinks", url: "drinks-placeholder.jpg" },
  #     "Quick-Fix" => { name: "Quick-Fix", url: "quick-fix-placeholder.jpg" },
  #     "Appetizers" => { name: "Appetizers", url: "appetizers-placeholder.jpg" },
  #     "Gluten-Free" => { name: "Gluten-Free", url: "gluten-free-placeholder.jpg" },
  #     "Vegetarian" => { name: "Vegetarian", url: "vegetarian-placeholder.jpg" }
  #   }
  # end
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<div class="banner">
  <div class="gradient"></div>
  <%= image_tag "banner1.jpg", class: "mainpage-banner-img" %>
  <div class="banner-content">
    <h1>Add a New Recipe to <%= @category.name %></h1>
    <p>Add something tasty to your collection.</p>
  </div>
</div>

<div class="new-form">
  <%= simple_form_for [@category, @bookmark] do |f| %>
    <div class="form-item"><%= f.input :recipe_id, collection: Recipe.all, label_method: :name, value_method: :id, prompt: 'Select a Recipe', as: :select %></div>
    <%= f.input :comment %>
    <%= f.button :submit, 'Add Recipe', class: 'btn btn-primary', class: "button-create" %>
  <% end %>
</div>

<%= link_to "Back to #{@category.name}", category_path(@category), class: "button" %>
<%# <%= link_to "See All", categories_path %>

app/views/categories/index.html.erb
<div class="banner">
  <div class="gradient"></div>
  <%= image_tag "banner1.jpg", class: "mainpage-banner-img" %>
  <div class="banner-content">
    <h1>The Alchemist's Cookbook</h1>
    <p>Craft Your Own Culinary Magic, One Recipe at a Time.</p>
  </div>
</div>

  <div class="description"><p>Bookmark and comment on your favorite recipes, creating a personalized collection of culinary magic. Keep your kitchen grimoire organized and accessible, all in one place.</p></div>
<div class="container">
  <div class="list">
    <% @categories.each do |category| %>
      <%= link_to category_path(category), class: "link" do %>
        <div class="card">
          <div class="gradient"></div>
          <% if category.image.present? %>
            <%= image_tag "#{category.image}", class: "img card-image" %>
          <% elsif category.bookmarks.exists? %>
            <% first_bookmark = category.bookmarks.first %>
              <% if first_bookmark.recipe.present? %>
                <%= image_tag first_bookmark.recipe.image_url, class: "img card-image" %>
              <% end %>
          <% else %>
                <%# <%= image_tag "placeholder.png", class: "card-image" %> <!-- Fallback image -->
              <%= image_tag default_category_image(category.name), class: "img card-image" %>
          <% end %>
            <div class="card-contents">
          <h2><%= category.name %></h2></div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= link_to "Create New Category", new_category_path,  class: "button new-button" %>

app/views/categories/new.html.erb
<div class="banner">
  <div class="gradient"></div>
  <%= image_tag "banner1.jpg", class: "mainpage-banner-img" %>
  <div class="banner-content">
    <h1>Add a New Category</h1>
    <p>Think we've missed something, add it below.</p>
  </div>
</div>

<div class="new-form">
<%= simple_form_for @category do |f| %>
  <%= f.input :name, label: 'Category Name:', class: "form-item" %>
  <%= f.input :image, as: :file, label: 'Upload Image (optional)', class: "form-item" %>
  <%# <%= f.input :default_image, as: :hidden %>
    <%# <div class="image-dropdown"> %>
    <%# <button type="button" class="dropdown-button"> %>
      <%# Select an Image %>
    <%# </button> %>
    <%# <div class="dropdown-menu"> %>
      <%# <% @default_image_urls.each do |key, value| %>
        <%# <div class="dropdown-option" data-image="<%= value[:url] %>
        <%# " data-name="<%= value[:name] %>
          <%# <%= image_tag value[:url], class: "dropdown-image" %>
        <%# </div> %>
      <%# <% end %>
    <%# </div> %>
  <%# </div> %>
  <%= f.submit 'Create Category', class: "button-create" %>
<% end %>
</div>
<%# <%= link_to "Back to All Categories", categories_path %>

app/views/categories/show.html.erb
<div class="banner">
  <div class="gradient"></div>
  <% if @category.image.present? %>
    <%= image_tag "#{@category.image}", class: "mainpage-banner-img" %>
  <% elsif @category.bookmarks.exists? %>
    <% first_bookmark = @category.bookmarks.first %>
      <%= image_tag first_bookmark.recipe.image_url, class: "img card-image" %>
  <% elsif @category.default_image.present? %>
    <%= image_tag "#{@category.default_image}", class: "mainpage-banner-img" %>
  <% else %>
    <%= image_tag "#{default_category_image(@category.name)}", class: "mainpage-banner-img" %>
  <% end %>
  <div class="banner-content">
    <h1><%= @category.name %></h1>
    <p>See all the delicious meals below</p>
  </div>
</div>


<div class="container">
  <div class="list">
    <% @bookmarks.each do |bookmark| %>
      <div class="show-card">
        <%= image_tag "#{bookmark.recipe.image_url}", class: "show-card-image" %>
        <div class="show-card-contents">
          <h3><strong><%= bookmark.recipe.name %></strong></h3>
          <p><%= bookmark.comment %></p>
          <%# <p><%= bookmark.recipe.description %></p>
          <%= link_to "🗑️", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "button-delete" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= link_to 'Add Bookmark', new_category_bookmark_path(@category), class: "button" %>
<h2>Reviews</h2>
<div class="reviews-container">
  <div class="reviews-list">
  <% @reviews.each do |review| %>
    <%  if review.valid? %>
      <div class="review">
        <p><%= '⭐️' * review.rating %>:
        <%= review.content %>
        <%# <% raise %>
        <%# <%= link_to "Delete", review_path(review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></p>
      </div>
    <% end %>
  <% end %>
  </div>
  <div class="form">
    <%= simple_form_for [@category, @category.reviews.new] do |f| %>
      <div class="star-rating">
        <% 5.downto(1) do |i| %>
          <%= f.radio_button :rating, i, id: "star#{i}" %>
          <label for="star<%= i %>" title="<%= i %> stars">
          &#9733;
          </label>
        <% end %>
      </div>
      <%= f.input :content, as: :text, label: false, placeholder: "Your Review" %>
      <%# <%= f.input :rating, as: :select, collection: 0..5, label: "Rating (0 to 5)" %>
      <%= f.button :submit, "Submit Review", class: "button-submit" %>
    <% end %>
  </div>
</div>
<%# <%= link_to "Add a Review", new_category_review_path(@category) %>
<%# <%= link_to "See All Categories", categories_path, class: "button" %>
<%# <%= link_to "Delete", category_path(@category), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/layouts/_navbar.html.erb
<!-- _navbar.html.erb -->
<div class="navbar">
  <div class="navbar-logo">
    <%= image_tag "logo2.png", class: "logo", id: "main-logo" %>
  </div>
  <div class="menu">
  <ul class="navbar-links">
    <li><a href="<%= root_path %>">Home</a></li>
    <li><a href="<%= new_category_path %>">New Category</a></li>
    <%# <li><a href="/about">About</a></li>
    <li><a href="/contact">Contact</a></li> %>
  </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Cookbook" %></title>
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Alice&family=Della+Respira&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap" rel="stylesheet">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# <link rel="stylesheet" href="application.css"> %>
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/reviews/new.html.erb
<h1>New Review for <%= @category.name %></h1>

<%= simple_form_for [@category, @review] do |f| %>
  <%= f.input :content, as: :text, label: "Your Review" %>
  <%= f.input :rating, as: :select, collection: 0..5, label: "Rating (0 to 5)" %>
  <%= f.button :submit, "Submit Review" %>
<% end %>

<%= link_to "Delete", review_path(@review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<%= link_to "Back to #{@category.name}", class: "btn btn-secondary" %>
<%= link_to "Back to All Categories", categories_path %>